### ISSUE TITLE
Don't allow project names characters not allowed in subdomains

### ISSUE THREAD

**Issue by benstein** [twilio-labs/twilio-run#71]
I have a project name_with_underscores, but when I do serverless:deploy it (correctly) fails to deploy with that name b/c it's not valid. Maybe disallow project names that won't be valid later? Or catch the error with instructions on how to resolve/rename it.

**Comment by dkundel** [comment]
I'd say let's primarily add a check on the deploy command that sends an appropriate error message with a suggestion to use `--service-name` to override or to change it in the package.json.

We can add a warning or error inside the project creation as well. But the primary check would be in the deployment since people could rename in between anyways.

**Comment by benstein** [comment]
Instructions on HOW to rename the project in the text as well would be
helpful.
