### ISSUE TITLE
Feature Request: Total Execution time for a function run

### ISSUE THREAD

**Issue by ShelbyZ** [twilio-labs/twilio-run#72]
With a Twilio Function we have a limited resource time and need to try and work within a 5 second time window.  Turning up logging via logLevel/detailedLogs does not give an 'at-a-glance' total execution time for a ran function:

![image](https://user-images.githubusercontent.com/1033099/62970843-3c563380-bdc5-11e9-9408-748f8cded6b1.png)

Looking at the Function exuction line we can get an estimate of the execution time since the last log statement.

We could make use of [console.time(...)](https://developer.mozilla.org/en-US/docs/Web/API/Console/time) in routes.ts like:

```JavaScript
const FUNCTION_LABEL = 'Function Execution';

try {
    console.time(FUNCTION_LABEL);
    fn(context, event, callback);
    console.timeEnd(FUNCTION_LABEL);
} catch (err) {
    console.timeEnd(FUNCTION_LABEL);
    callback(err);
}
```

There might be an easier way to achieve this with the current logger, but I hadn't dived down into it.

**Comment by dkundel** [comment]
Definitely love the idea. I think we shouldn't use console.time purely because we don't have access to where it writes but we should have this feature.

I think it has the caveat that it's only execution time and therefore not precise enough to give a time that reflects what's happening in the deployed version but it's a good indicator!

**Comment by dkundel** [comment]
Thank you for contributing this @ShelbyZ! Closing this issue because #81 has been merged
