### ISSUE TITLE
Allow to set an optional GitHub API token to circumvent rate limiting

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/twilio-run#90]
In #86 we added a better error message for GitHub API failures. 

However, if the rate limit error is thrown the error message they get is not the most useful one for people. I'd be in favor of catching that one specifically and replying with something like this:

```
We are sorry but we failed fetching the requested template from GitHub because your IP address has been rate limited. Please try the following to resolve the issue:
- Change your WiFi or make sure you are not connected to a VPN that might cause the rate limiting

If the issue persists you can try one of the two options:
- Get a GitHub developer token following https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line (no permissions needed) and add it as `TWILIO_SERVERLESS_GITHUB_TOKEN` to your environment variables
- Wait for a few minutes up to an hour and try again.
```

For this we'd have to make sure to pass `TWILIO_SERVERLESS_GITHUB_TOKEN` to the GitHub API if it's available.

**Comment by badsketch** [comment]
Hey, I'd be interested in tackling this issue @dkundel

**Comment by dkundel** [comment]
Yes @badsketch pleae go ahead with this :) Thank you!

**Comment by badsketch** [comment]
@dkundel Does this include adding `--github-token` as a flag option for the `new` command?

On one hand it adds flexibility to how a user uses the cli. On the other hand, it might be out of place since the only time they see it is if they're using `new` extensively to the point of rate limiting. And at that point, they would probably add it to `.env` as a permanent solution instead of flag as a one time use.

I'm still new to contributing to a CLI helper so I don't know all of the use cases. Thoughts? 🙂

**Comment by badsketch** [comment]
Oh, I think I misread what environmental variables meant. Aside from adding the api variable in the `.env` file, `TWILIO_SERVERLESS_GITHUB_TOKEN=xxxx twilio-run new ` would already be a way to specify environment variables via the command line so I guess there wouldn't be a need to add `--github-token` as an option flag right?

**Comment by dkundel** [comment]
Yeah just using the env variable would be totally sufficient. Don't think we need to have a separate flag. Thank you :) and sorry for the delay. I was traveling.

**Comment by badsketch** [comment]
No worries  🙂Thanks for the clarification
